export const SalesLetter = [
  { field: 'date_start', name: 'FECHA', checkbox: true },
  { field: 'spend', name: '$Inv.', checkbox: true },
  { field: 'impressions', name: '#Imp.', checkbox: false },
  { field: 'cpm', name: '$CPM', checkbox: false },
  { field: 'reach', name: '#Reach', checkbox: false },
  { field: 'frequency', name: '#Frec.', checkbox: false },
  { field: 'clicks', name: '#Clics', checkbox: true },
  { field: 'clicks_organic', name: '#Clicks Organicos', checkbox: true },
  { field: 'cpc', name: '$CPC', checkbox: true },
  { field: 'ctr', name: '%CTR', checkbox: true },
  { field: 'views', name: '#LV', checkbox: true },
  { field: 'CTA', name: '#CTA', checkbox: true },
  { field: 'CKL', name: '#CKL', checkbox: true },
  { field: 'SLTCK', name: '%SLTCK', checkbox: true },
  { field: 'CPCKL', name: '#CPCKL', checkbox: false },
  { field: 'CKOR', name: '%CKOR', checkbox: true },
  { field: 'sales', name: '#Sales', checkbox: true },
  { field: 'CAC', name: '$CAC', checkbox: true },
  { field: 'FCR', name: '%FCR', checkbox: true },
  { field: 'SPCR', name: '%SPCR', checkbox: true },
  { field: 'CKCR', name: '%CKCR', checkbox: true },
  { field: 'Cohort', name: '#Cohort', checkbox: true },
  { field: 'US', name: '#US', checkbox: true },
  { field: 'UCR', name: '%UCR', checkbox: true },
  { field: 'dws', name: '#DWS', checkbox: true },
  { field: 'B', name: '#B', checkbox: true },
  { field: 'BR', name: '%BR', checkbox: true },
  { field: 'revenue', name: '$Revenue', checkbox: true },
  { field: 'cash', name: '$Cash', checkbox: true },
  { field: 'ACV', name: '$ACV', checkbox: true },
  { field: 'profit', name: '$Profit', checkbox: true },
  { field: 'EPC', name: '$EPC', checkbox: true },
  { field: 'EPV', name: '$EPV', checkbox: false },
  { field: 'account_currency', name: '$Cuenta de dinero', checkbox: true },
]

const SalesCall = [
  { field: 'date_start', name: 'FECHA', checkbox: true },
  { field: 'spend', name: '$Inv.', checkbox: true },
  { field: 'impressions', name: '#Imp.', checkbox: false },
  { field: 'cpm', name: '$CPM', checkbox: false },
  { field: 'reach', name: '#Reach', checkbox: false },
  { field: 'frequency', name: '#Frec.', checkbox: false },
  { field: 'clicks', name: '#Clics', checkbox: true },
  { field: 'clicks_organic', name: '#Clicks Organicos', checkbox: true },
  { field: 'cpc', name: '$CPC', checkbox: true },
  { field: 'ctr', name: '%CTR', checkbox: true },
  { field: 'views', name: '#LV', checkbox: true },
  { field: 'leeds', name: '#Leads', checkbox: true },
  { field: 'CPL', name: '$CPL', checkbox: true },
  { field: 'LCR', name: '%LCR', checkbox: true },
  { field: 'AT', name: '#AT', checkbox: true },
  { field: 'CPAT', name: '$CPAT', checkbox: false },
  { field: 'ATR', name: '%ATR', checkbox: true },
  { field: 'CTA', name: '#CTA', checkbox: false },
  { field: 'LTA', name: '%LTA', checkbox: true },
  { field: 'CKOR', name: '%CKOR', checkbox: true },
  { field: 'Aps', name: '#Aps.', checkbox: true },
  { field: 'CPAp', name: '$CPAp.', checkbox: false },
  { field: 'Apr', name: '%APR', checkbox: true },
  { field: 'LTAp', name: '%LTAp.', checkbox: true },
  { field: 'B', name: '#B', checkbox: true },
  { field: 'CPB', name: '$CPB', checkbox: true },
  { field: 'BR', name: '%BR', checkbox: true },
  { field: 'LTB', name: '%LTB', checkbox: true },
  { field: 'LTBD', name: '#LTBD', checkbox: false },
  { field: 'sales', name: '#Sales', checkbox: true },
  { field: 'CAC', name: '$CAC', checkbox: true },
  { field: 'SCR', name: '%SCR', checkbox: true },
  { field: 'FCR', name: '%FCR', checkbox: true },
  { field: 'BTS', name: '%BTS', checkbox: true },
  { field: 'Cohort', name: '#Cohort', checkbox: false },
  { field: 'BTSD', name: '#BTSD', checkbox: false },
  { field: 'sutds', name: '#SUTSD', checkbox: false },
  { field: 'revenue', name: '$Revenue', checkbox: true },
  { field: 'cash', name: '$Cash', checkbox: true },
  { field: 'ACV', name: '$ACV', checkbox: true },
  { field: 'profit', name: '$Profit', checkbox: true },
  { field: 'PPB', name: '$PPB', checkbox: true },
  { field: 'EPC', name: '$EPC', checkbox: false },
  { field: 'EPV', name: '$EPV', checkbox: false },
  { field: 'EPL', name: '$EPL', checkbox: false },
  { field: 'EPA', name: '$EPA', checkbox: false },
  { field: 'EPB', name: '$EPB', checkbox: true },
  { field: 'account_currency', name: '$Cuenta de dinero', checkbox: true },
]

const SalesWebinar = [
  { field: 'date_start', name: 'FECHA', checkbox: true },
  { field: 'spend', name: '$Inv.', checkbox: true },
  { field: 'impressions', name: '#Imp.', checkbox: false },
  { field: 'cpm', name: '$CPM', checkbox: false },
  { field: 'reach', name: '#Reach', checkbox: false },
  { field: 'frequency', name: '#Frec.', checkbox: false },
  { field: 'clicks', name: '#Clics', checkbox: true },
  { field: 'clicks_organic', name: '#Clicks Organicos', checkbox: true },
  { field: 'cpc', name: '$CPC', checkbox: true },
  { field: 'ctr', name: '%CTR', checkbox: true },
  { field: 'views', name: '#LV', checkbox: true },
  { field: 'leeds', name: '#Leads', checkbox: true },
  { field: 'CPL', name: '$CPL', checkbox: true },
  { field: 'LCR', name: '%LCR', checkbox: true },
  { field: 'AT', name: '#AT', checkbox: true },
  { field: 'CPAT', name: '$CPAT', checkbox: false },
  { field: 'ATR', name: '%ATR', checkbox: true },
  { field: 'CTA', name: '#CTA', checkbox: false },
  { field: 'LTA', name: '%LTA', checkbox: true },
  { field: 'SLTCK', name: '%SLTCK', checkbox: false },
  { field: 'CKL', name: '#CKL', checkbox: true },
  { field: 'CPCKL', name: '#CPCKL', checkbox: false },
  { field: 'CKOR', name: '%CKOR', checkbox: true },
  { field: 'sales', name: '#Sales', checkbox: true },
  { field: 'CAC', name: '$CAC', checkbox: true },
  { field: 'SPCR', name: '%SPCR', checkbox: false },
  { field: 'CKCR', name: '%CKCR', checkbox: true },
  { field: 'FCR', name: '%FCR', checkbox: true },
  { field: 'Cohort', name: '#Cohort', checkbox: false },
  { field: 'revenue', name: '$Revenue', checkbox: true },
  { field: 'cash', name: '$Cash', checkbox: true },
  { field: 'ACV', name: '$ACV', checkbox: true },
  { field: 'profit', name: '$Profit', checkbox: true },
  { field: 'EPC', name: '$EPC', checkbox: false },
  { field: 'EPV', name: '$EPV', checkbox: false },
  { field: 'EPL', name: '$EPL', checkbox: false },
  { field: 'EPA', name: '$EPA', checkbox: false },
  { field: 'account_currency', name: '$Cuenta de dinero', checkbox: true },
]

const Launch = [
  { field: 'date_start', name: 'FECHA', checkbox: true },
  { field: 'spend', name: '$Inv.', checkbox: true },
  { field: 'impressions', name: '#Imp.', checkbox: false },
  { field: 'cpm', name: '$CPM', checkbox: false },
  { field: 'reach', name: '#Reach', checkbox: false },
  { field: 'frequency', name: '#Frec.', checkbox: false },
  { field: 'clicks', name: '#Clics', checkbox: true },
  { field: 'clicks_organic', name: '#Clicks Organicos', checkbox: true },
  { field: 'cpc', name: '$CPC', checkbox: true },
  { field: 'ctr', name: '%CTR', checkbox: true },
  { field: 'views', name: '#LV', checkbox: true },
  { field: 'leeds', name: '#Leads', checkbox: true },
  { field: 'CPL', name: '$CPL', checkbox: true },
  { field: 'LCR', name: '%LCR', checkbox: true },
  { field: 'AT', name: '#AT', checkbox: true },
  { field: 'CPAT', name: '$CPAT', checkbox: false },
  { field: 'ATR', name: '%ATR', checkbox: true },
  { field: 'CTA', name: '#CTA', checkbox: false },
  { field: 'LTA', name: '%LTA', checkbox: true },
  { field: 'SLTCK', name: '%SLTCK', checkbox: false },
  { field: 'CKL', name: '#CKL', checkbox: true },
  { field: 'CPCKL', name: '#CPCKL', checkbox: false },
  { field: 'CKOR', name: '%CKOR', checkbox: true },
  { field: 'sales', name: '#Sales', checkbox: true },
  { field: 'CAC', name: '$CAC', checkbox: true },
  { field: 'SPCR', name: '%SPCR', checkbox: false },
  { field: 'CKCR', name: '%CKCR', checkbox: true },
  { field: 'FCR', name: '%FCR', checkbox: true },
  { field: 'Cohort', name: '#Cohort', checkbox: false },
  { field: 'revenue', name: '$Revenue', checkbox: true },
  { field: 'cash', name: '$Cash', checkbox: true },
  { field: 'ACV', name: '$ACV', checkbox: true },
  { field: 'profit', name: '$Profit', checkbox: true },
  { field: 'EPC', name: '$EPC', checkbox: false },
  { field: 'EPV', name: '$EPV', checkbox: false },
  { field: 'EPL', name: '$EPL', checkbox: false },
  { field: 'EPA', name: '$EPA', checkbox: false },
  { field: 'account_currency', name: '$Cuenta de dinero', checkbox: true },
]

const Ecommerce = [
  { field: 'date_start', name: 'FECHA', checkbox: true },
  { field: 'spend', name: '$Inv.', checkbox: true },
  { field: 'impressions', name: '#Imp.', checkbox: false },
  { field: 'cpm', name: '$CPM', checkbox: false },
  { field: 'reach', name: '#Reach', checkbox: false },
  { field: 'frequency', name: '#Frec.', checkbox: false },
  { field: 'clicks', name: '#Clics', checkbox: true },
  { field: 'clicks_organic', name: '#Clicks Organicos', checkbox: true },
  { field: 'cpc', name: '$CPC', checkbox: true },
  { field: 'ctr', name: '%CTR', checkbox: true },
  { field: 'views', name: '#LV', checkbox: true },
  { field: 'CTA', name: '#CTA', checkbox: true },
  { field: 'CKL', name: '#CKL', checkbox: true },
  { field: 'SLTCK', name: '%SLTCK', checkbox: true },
  { field: 'CPCKL', name: '#CPCKL', checkbox: false },
  { field: 'CKOR', name: '%CKOR', checkbox: true },
  { field: 'sales', name: '#Sales', checkbox: true },
  { field: 'CAC', name: '$CAC', checkbox: true },
  { field: 'FCR', name: '%FCR', checkbox: true },
  { field: 'SPCR', name: '%SPCR', checkbox: true },
  { field: 'CKCR', name: '%CKCR', checkbox: true },
  { field: 'Cohort', name: '#Cohort', checkbox: true },
  { field: 'US', name: '#US', checkbox: true },
  { field: 'UCR', name: '%UCR', checkbox: true },
  { field: 'dws', name: '#DWS', checkbox: true },
  { field: 'B', name: '#B', checkbox: true },
  { field: 'BR', name: '%BR', checkbox: true },
  { field: 'revenue', name: '$Revenue', checkbox: true },
  { field: 'cash', name: '$Cash', checkbox: true },
  { field: 'ACV', name: '$ACV', checkbox: true },
  { field: 'profit', name: '$Profit', checkbox: true },
  { field: 'EPC', name: '$EPC', checkbox: true },
  { field: 'EPV', name: '$EPV', checkbox: false },
  { field: 'account_currency', name: '$Cuenta de dinero', checkbox: true },
]